DATABASE_CONNECTION_STRING = 'mysql://root:1234@localhost:3306/realestates'

MAX_PRICE = 1400
MIN_PRICE = 125
MIN_LIVABLE_AREA = 6
MAX_LIVABLE_AREA = 150
MAX_NR_ROOMS = 8
MAX_PRICE_PER_SQ_METER = 30
RON_TO_EURO_CONVERSION_RATE = 4.7


SAVE_DIR = r'C:\Users\pohri\Desktop\An 4\Licenta\saved_models'

FLASK_PORT = 12345